[package]
name = "tron"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst_gltf = "0.7.0"
amethyst = { version = "0.12.0", features = ["vulkan"] }
serde = { version = "1", features = ["derive"] }
specs-derive = "0.4.0"